### ISSUE TITLE
Anzahl der Restart-Versuche von owfs2mqtt.pl begrenzen

### ISSUE THREAD

**Issue by cmonty14** [mschlenstedt/LoxBerry-Plugin-1-Wire-NG#11]
Im Fehlerfall wird endlos versucht, das Programm owfs2mqtt.pl zu restarten.
Es wäre sinnvoll, die Anzahl der Start-Versuche auf eine Anzahl kleiner 10 zu begrenzen.

**Comment by mschlenstedt** [comment]
In Version 2.0 integtriert.
