### ISSUE TITLE
iButtons werden nicht erkannt

### ISSUE THREAD

**Issue by mschlenstedt** [mschlenstedt/LoxBerry-Plugin-1-Wire-NG#8]
https://www.loxforum.com/forum/projektforen/loxberry/plugins/227489-plugin-1-wire-ng?p=247776#post247776

**Comment by mschlenstedt** [comment]
KOmmt ins nächste Release. Default-Einstellung ist nun "Uncached Reading".

**Comment by challo2018** [comment]
Hier gab es zusätzlich noch folgendes Thema bei iButtons:

#######
Zusätzlich habe ich noch unter Zeile 300 folgendes eingefügt, damit der Bus auf ein ungültigen Wert gesetzt wird wenn der Button nicht mehr verbunden ist. Damit ist die Auswertung in der LoxConfig einfacher. Hier kann vielleicht aber noch eine bessere Variante wie diese hier gefunden werden:
if ($value eq "0")
{
$data{"bus"} = "-9999";
}
#######

Hast du hier auch eine Änderung eingebaut?

**Comment by mschlenstedt** [comment]
Habe ich noch nicht eingebaut, weil mir der Sinn nicht ganz klar war. Warum nutzt du nicht die Option „Check Präsenz“ in der Device Konfigursation, um in LoxConfig auszuwerten ob der iButton am Bus ist oder nicht?

**Comment by challo2018** [comment]
Ich verwende iButtons zum öffnen von Türen. An verschiedenen Türen ist daher ein Leser, der jeweils auf einem extra Bus hängt. 
Wenn jetzt ein Button erkannt wird, werte ich zusätzlich aus auf welchem Bus er erkannt wurde und öffne die Tür. 
Aktuell  bleibt in "Bus" der zuletzt erkannte Bus stehen. Daher kann es vorkommen, dass die falsche Tür geöffnet wird.
Aus meiner Sicht wäre es daher am besten wenn "Bus" auch zurück gesetzt wird sobald der Button nicht mehr verbunden ist.

**Comment by mschlenstedt** [comment]
Ah, verstehe. Wäre es OK wenn ich das mit "Check Präsenz" verbinde, d.h. der Bus wird nur auf "-9999" gesetzt, wenn für den iButton auch "Check Präsenz" aktiviert wurde?

Und ich wprde dann anstelle "-9999" lieber "-1" nehmen.

**Comment by challo2018** [comment]
Ja ich denke das macht Sinn. -1 ist auch in Ordnung. Ich habe nur -9999 gewählt damit sicher Erkennbar ist, dass es durch meine Anpassung gesetzt wurde. Hab nicht den ganzen Code überblickt um eventuell andere Fälle zu sehen ;-)

Vielen Dank!

**Comment by mschlenstedt** [comment]
Installier mal bitte den letzten Master und schaue, ob es so funktioniert. Wenn "check present" am Device jetzt aktiviert ist und das Device ist nicht an irgendeinem Bus, wird der Bus auf -1 gesetzt.

Aktuell schreibe ich den Bus ja so: "bus.0", "bus.1" usw. Macht es Sinn das gleich ohne Text, also "0", "1" usw. zu schreiben? Dann wäre die Auswertung in LoxConfig noch einfacher.

**Comment by challo2018** [comment]
Danke! Ich versuchs heute abend zu testen! Das mit dem Bus macht auf jeden Fall Sinn. Ich hab bisher eine Conversion dafür im MQTT Gateway... ;-)
![2021-08-24_18h39_10](https://user-images.githubusercontent.com/42739411/130655950-95151bc8-9bdc-4a82-92e9-26b3babb5794.png)

**Comment by challo2018** [comment]
Habs mal das preRelease instsalliert und dann die owfs2mqtt.pl ausgetauscht. Ich habe danach probleme mit meinen türen.
Die Regex in Zeile 371 scheint mir immernoch falsch. Die Buttons werden nur sehr langsam erkannt. Wenn ich die Zeile wie folgt ändere passt es bei mir : ( $_ =~ /^\/(\d){2}.*$/ )

Die Anpassung für Bus = -1 hast du bei "Scan for values - default configs" gemacht. Da die Buttons aber eine CustomConfig haben muss diese zu auch zu  "Scan for values - custom configs". So wie es momentan im #Publish steht funktioniert es aber bei mir auch nicht.  Da die IF Abfrage nicht true wird.

Wenn du mehr infos brauchst meld dich.

**Comment by mschlenstedt** [comment]
Danke für's Testen!

Zum Bus = -1: Das war mein Denkfehler. Ich hab's noch einmal angepasst. So sollte es jetzt klappen. Probiere bitte noch einmal.

Zum Regex: Welche Zeile meinst Du genau? Finde in Zeile 371 nichts... Am Besten mal vorne auf die Zeilennummer klicken und Permalink auswählen und hier posten.

Aber wenn ich mich recht erinnere hatte ich doch damals etwas mit \d){2}.*, aber da werden keine Sensoren erkannt, die als Family ID z. B. "1B" haben. Verstehe auch noch nicht so ganz, warum der Regex die Erkennung verlangsamt... Das müsste ich mir noch einmal anschauen.

**Comment by challo2018** [comment]
Jetzt sieht es gut aus. Ich kann leider erst morgen Nachmittag testen. Melde mich dann.

Sorry wegen der Regex meine ich:
 https://github.com/mschlenstedt/LoxBerry-Plugin-1-Wire-NG/blob/b253283eab193f94781e5dbed2b61841878b23c0/bin/owfs2mqtt.pl#L366

Da scheint es ein Problem zu geben. Muss mir aber auch nochmal genau anschauen was diese regex macht. Erinnere mich nicht mehr genau...

**Comment by challo2018** [comment]
Super, funktioniert alles :-)

Vielen Dank!!

**Comment by mschlenstedt** [comment]
Perfekt! Ich mach ein Release draus.
