### ISSUE TITLE
Zum auffinden aller 1-wire Sensoren

### ISSUE THREAD

**Issue by leschNUX** [mschlenstedt/LoxBerry-Plugin-1-Wire-NG#9]
Hi,

wäre Super wenn du das so einbauen könntest, dann würde man alle Sensoren finden, das gleich muss in der index.cgi passieren.

Datei: owfs2mqtt.pl
# if ( $_ =~ /^\/bus\.\d*\/(/d){2}.*$/ ) {
gegen das 
if ( $_ =~ /^\/bus\.\d*\/[0-9a-fA-F]{2}.*$/ ) {

**Comment by mschlenstedt** [comment]
Lange hat's degauert ;-) Kommt ins nächste Release in den nächsten Tagen. Danke!
